# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a042f69fe36117560cee8e71cfd3308c8086056a8f6b9110da86ce7a81235eb3258a7ded3deb3f32fd46f2ca0af6f482e6964dd791776bfa7e9a3def836e045

test:
  secret_key_base: f78fa196630f6db8eddf92a52c06af736e838d9f243ea26f04e2ea75dd9935798c9d563c08f481721c23d976362ba1687743462fea39153cab9942a772fe95e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
